### ISSUE TITLE
Consider making options match simple-peer

### ISSUE THREAD

**Issue by JustMaier** [shanebloomer/webrtc-link#7]
Saw your comment on the simple-peer/lite issue and came here looking for a smaller alternative for browser only functionality. I really like what you have here. The code is more modern and much easier to read. Thank you!

Like you said in the comment on the issue, it's very close to the simple-peer spec, so close that I didn't notice that the `option` props and defaults changed. Would you consider doing one of the following:
- Add a small transition guide to the README that calls out specific changes
- OR adjust the options to mirror simple-peer

**Comment by shanebloomer** [comment]
The trouble with stating specific changes between the config of `simple-peer` and `webrtc-link` in the README is that it can be difficult to keep it up to date.

These are the current differences.

```
{
  dataChannelConfig: {}, -----> channelConfig: {}
  isInitiator: false, ------> initiator: false
  isTrickleIceEnabled: true, ------> trickle: true
  peerConnectionConfig: { iceServers: [] }, ------> config: { iceServers: [{ urls: 
 'stun:stun.l.google.com:19302' }, { urls: 'stun:global.stun.twilio.com:3478?transport=udp' }] },
  sdpTransformer: sdp => sdp, ------> sdpTransform: function (sdp) { return sdp }
  streams: []
}
```

**Comment by JustMaier** [comment]
Good to know. Maybe a Wiki page would be a better option since it's easier to change without having to do commits.
