### ISSUE TITLE
`Close` event never fired if `Error` event isn't captured

### ISSUE THREAD

**Issue by JustMaier** [shanebloomer/webrtc-link#8]
This might be intentional, if so, it just needs to be documented.

Steps to reproduce:
1. Connect a peer in a different browser tab.
2. Listen for `close` event
3. Close one of the tabs
4. An uncaught error is thrown and `close` event never fires.

**Comment by shanebloomer** [comment]
Hello Justin,

I have not been able to reproduce this issue on the latest version of `webrtc-link` (v2.0.0).

No changes have been made in the code to specifically address this.

Here's the example that I used. Signaling data is exchanged by copying and pasting it into the text box and clicking submit.

https://github.com/shanebloomer/webrtc-link-examples/tree/20f0699c2bb357c0abb8c0afaafd7891709c7a73

**Comment by JustMaier** [comment]
That's great news. Thanks for the time and energy you've put into this project @shanebloomer
